### ISSUE TITLE
The immich_postgres container consumes all server resources  

### ISSUE THREAD

**Issue by HowWof** [alextran1502/immich#102]
I don't know if it's a bug or a configuration problem but immich_postgres is consuming all server resources below the logs
[Logs](https://cloud.howwof.pl/f/7a0fc9a9767247feac52/)

**Comment by alextran1502** [comment]
Can you monitor with `docker stats` to see how much CPU/RAM `immich_postgres` is pulling?

If I remember correctly, you are running on Ubuntu Server 20.04, correct?

**Comment by HowWof** [comment]
67% to 93% of the processor.
RAM Consumption 2.7 GB swap 500 MB
You remember the system correctly

**Comment by alextran1502** [comment]
Is this behavior happening during idle or during the backup process?

**Comment by HowWof** [comment]
During idle time

**Comment by alextran1502** [comment]
Interesting, I am seeing mine at 0% during idle. Let me investigate this. 

What is your docker and docker-compose version?

**Comment by HowWof** [comment]
Docker version 20.10.14, build a224086
docker-compose version 1.29.2, build 5becea4c

**Comment by Eidenz** [comment]
The exact same issue happened to me today. 99% CPU on idle from postgres.

Docker version 20.10.14
Docker-compose version 1.29.2, build 5becea4c
OS: Ubuntu 20.04.4 LTS x64

**Comment by alextran1502** [comment]
@Eidenz Can access to the database container with

```
docker exec -it immich_postgres psql -U postgres
```

then

```
select * from pg_stat_activity WHERE state='active';
```

And let me know the output?

**Comment by HowWof** [comment]
docker exec -it immich_postgres psql -U postgres
give:
psql (14.2 (Debian 14.2-1.pgdg110+1))
Type "help" for help.
select * from pg_stat_activity WHERE state='active';
give:
LINE 1: docker exec -it immich_postgres psql -U postgres
        ^

**Comment by alextran1502** [comment]
Is this issue still relevant?
