### ISSUE TITLE
[BUG] Backup stuck after 8 elements

### ISSUE THREAD

**Issue by Eidenz** [alextran1502/immich#106]
I have a total of 218 assets I want to backup but after uploading 8 of them, the app is stuck at 100% on asset 210.
I cannot see anything in the logs: none of the docker containers shows anything during the upload attempt period (except for redis which says it successfully saved the changes).

I let the app run for over 30min to see if it was just a very slow/long upload, but the problem is still there.

**To Reproduce**
1. Attempt to upload more than 8 files through the android app?

**Expected behavior**
All uploads should succeed.

**Screenshots**
![Screenshot_2022-04-04-15-13-42-999_app alextran immich](https://user-images.githubusercontent.com/27901016/161552291-291ee289-0c35-46a0-94d6-2bebb98b080b.jpg)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 1.5.0

**Smartphone (please complete the following information):**
 - Device: Mi 11
 - OS: MIUI 13
 - Version 1.5.0 build.8

**Additional context**
I also tried without TensorFlow (removed the immich_microservices) but it also fails at the exact same asset.

**Comment by alextran1502** [comment]
Is this photo or video something you can share? Or can you get me the file information from the phone?

**Comment by alextran1502** [comment]
The assets are uploaded based on chronological order, newest to oldest, you can take a look at all the assets that have been backup and see which one it is trying to upload and track them down from your gallery.

**Comment by Eidenz** [comment]
I've traced it back to a random meme picture in webp format (ZBsUr45_d.webp). Do you need it?

**Comment by Eidenz** [comment]
Oh okay, that makes sense. Thanks c:

**Comment by Eidenz** [comment]
I'm actually having the same issue with another picture, but it's a `jpg` this time..

This one was taken by my phone (it's a photo of my cat).

**Comment by alextran1502** [comment]
This issue is fixed in #108. I will push out an updated version of the app in the next few days :) Sorry for the inconvenience
