### ISSUE TITLE
[BUG] Backup in upload loop on specific asset

### ISSUE THREAD

**Issue by thefirstofthe300** [alextran1502/immich#110]
**Describe the bug**
Backup of a specific asset (unknown if picture or video) from Android app goes from 0-100% and then restarts. 

**To Reproduce**
I'm sure if I knew what asset it was trying to upload, I could give you the file to troubleshoot.

**Expected behavior**
Backup completes

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Latest Android 12

First off, this is an awesome little project that's providing me with exactly the experience I want. I love how it places the emphasis on the mobile device.

Secondly, what's the best way to provide debug logs from my Android device for you?

**Comment by Eidenz** [comment]
Pretty sure that's the same as #106, which was fixed a few hours ago and is awaiting APK rebuild.

**Comment by alextran1502** [comment]
@thefirstofthe300 @Eidenz is correct, I will push out a new release soon

**Comment by alextran1502** [comment]
@thefirstofthe300 @Eidenz The issue should be fixed in the [latest release](https://github.com/alextran1502/immich/releases/tag/v1.6.0_10-dev)

**Comment by alextran1502** [comment]
> @alextran1502 unfortunately, the issue doesn't seem to be fixed on my end. I did update my android app & server though (1.6.0 build.10 & 1.6.0).
> 
> 
> 
> The upload is stuck on a `jpg` picture taken from my phone camera.


Hmmm 🤔 can you share the image?

**Comment by alextran1502** [comment]
@Eidenz This is a strange problem because I don't have any problem backing up the photo on my device (Samsung S9) and Android emulator. You said it is stuck on the image and not backing up anything else, correct?

Do you have a way to get the log file and send them to me?

**Comment by Eidenz** [comment]
Hm.. I've retried to get some logs and it just started syncing without issue.

I was at work earlier, so maybe my the network there was blocking the request or something. Sorry about that, all good then xp

**Comment by notarobot63** [comment]
Hi, I think I got the same issue here. Backup is stuck at 2558 assets remaining and is looping. Newly taken photos are backed up without a problem though. I m on last versions both on phone and one server. 
Let me know how I can provide more information that can help.

**Comment by alextran1502** [comment]
@notarobot63 Can you get me the metadata of the video? I.e file extension, file size...etc? Is this video something you can share?

**Comment by notarobot63** [comment]
@alextran1502 Nevermind I'm not sure that this file is the problem as I'm not sure it's the one beeing backuped. If I read you correctly Immich backup files chronologically, but I'm missing files after Feb 27, 2022 and no more backup before this date. Not sure on how to debug this

**Comment by alextran1502** [comment]
@notarobot63 can you check in your photo gallery app of your phone what is the next asset right after the last asset that is shown on Immich's timeline? 

What is your phone model?

**Comment by notarobot63** [comment]
Here are the video's metadata
![Screenshot_20220411-123019](https://user-images.githubusercontent.com/51323017/162722642-1ddec1b4-f5a2-4edf-ae2f-1eda34016112.jpg)
I'm one OnePlus 7T android 11

**Comment by notarobot63** [comment]
Nevermind, client_max_body_size on my reverse proxy solved it. Sorry I didn't thought about it before.

**Comment by alextran1502** [comment]
@notarobot63 No problem, I ran into that issue a while back as well :) I am glad it is working for you!

**Comment by alextran1502** [comment]
I am closing this issue, if you have any further questions, please reopen this issue.
