### ISSUE TITLE
Selective Backup in App

### ISSUE THREAD

**Issue by ShiniGandhi** [alextran1502/immich#120]
I think being able to select which directories on my phone are backed up would be extremely useful. I have over 10,000 photos from WhatsApp and I really don't want all of them backed up.

**Comment by GregTroar** [comment]
Yep exactly same for me, would like to backup only camera photos, not all whatsapp

**Comment by alextran1502** [comment]
Album selection has been implemented and will be available in the next release (later today, or tomorrow) 
![Selection Backup](https://user-images.githubusercontent.com/27055614/167127246-f07fef38-853b-4095-89fe-26f2809f87e1.png)
