### ISSUE TITLE
[new feature] web interface

### ISSUE THREAD

**Issue by spupuz** [alextran1502/immich#139]
web interface for user creation and for looking the backed up photos via browser

**Comment by JamesBelchamber** [comment]
Since Immich is written in Flutter this shouldn't be all that far-fetched :eyes:

**Comment by alextran1502** [comment]
Added in #172 - Closing this issue.

**Comment by spupuz** [comment]
so a web interface is now available?

**Comment by alextran1502** [comment]
@spupuz yes. Please check out the updated readme file for additional info, the docker-compose file is updated with the new web interface container, there is also a new value in the .env file that is required to run the app
