### ISSUE TITLE
[BUG] Android App not showing any assets at all

### ISSUE THREAD

**Issue by simonfromwales** [alextran1502/immich#146]
I've set up a Immich server on a Debian 11 VM on Proxmox. I have changed the CPU type to host as per the known issue in the readme.
The android app has the location and storage permission set to allowed.
When I click on select in the backup albums box, I get 'total unique assets 0' and nowhere to select any folders.
The 'backup progress:' is showing a spinning circle and doesn't seem to progress any further.
The server shows a new websocket connection so the android app is connecting to it.
Any suggestions as to what to do next to get it to work?

**Comment by alextran1502** [comment]
Can you share the screenshot of album selection screen? When you tap on the album, it would select it

**Comment by simonfromwales** [comment]
Thank you for your response.

Screenshot attached, there's no albums available to select.

![Screenshot_20220507-160320](https://user-images.githubusercontent.com/99139154/167268538-21c9485d-8b10-4faa-9e1d-e76cf5e0ae7c.png)

**Comment by alextran1502** [comment]
Hmm, it looks like it cannot see any albums on your device. Can you  uninstall and reinstall the app? When it asked for your permission to access the albums on the device when first navigate to the backup screen, can you set as allow all?

**Comment by simonfromwales** [comment]
I did think it was odd that the app didn't ask for any permissions at all.
So I manually set the two (location and storage) permissions to allowed.

I've just uninstalled and installed the app again. Still the same, didn't
ask me for permission.

**Comment by alextran1502** [comment]
I will take a look, can you let me know what is your device info?

**Comment by alextran1502** [comment]
I find this very strange, I've just tested again on both my Samsung S8 and Android Simulator, and both asked for permission when I opened the backup page. Can you go into **Settings -> Apps -> Immich -> Permissions** and help me take a screenshot of the allowed list?

**Comment by simonfromwales** [comment]
I am using Android 10 on Motorola Moto.

![image](https://user-images.githubusercontent.com/99139154/167287686-71acfd29-ec2c-43f8-b2cc-ab5f05b39e44.png)

**Comment by alextran1502** [comment]
Thank you, let me try the same version of Android on simulator and I will let you know

**Comment by alextran1502** [comment]
Found the bug in Android 10. I will work on it and push out a hotfix

**Comment by alextran1502** [comment]
The fix is being reviewed on PlayStore, I expect it will be approved in the next couple of hours. I will let you know once it is through.

**Comment by alextran1502** [comment]
@simonfromwales The new release is available on PlayStore. Can you update and try again?
Thanks

**Comment by simonfromwales** [comment]
That is working great now thank you!

**Comment by simonfromwales** [comment]
Thank you for your response.

Screenshot attached, there's no albums to select.
