### ISSUE TITLE
Feature: Prevent signup

### ISSUE THREAD

**Issue by RealOrangeOne** [alextran1502/immich#148]
Currently, it's possible for anyone with access to the server's API (which if it's connected to the internet, is everyone) to create a user account and begin using immich.

It'd be great if it were possible to prevent registration, probably through an environment variable. This way, the admin can manage creating accounts themselves, and then just keep the API disabled everywhen else.

**Comment by alextran1502** [comment]
In progress
<img width="2056" alt="Screen Shot 2022-05-19 at 18 08 27" src="https://user-images.githubusercontent.com/27055614/169418723-033281e0-49fe-43b5-b6e5-3256663c8dfe.png">

**Comment by alextran1502** [comment]
You can try out this feature by updating the repository and pulling the latest images for the docker services. There is a new environment variable you have to put in for this to work. Please check `.env.example` for more detail. I am closing this issue now.
