### ISSUE TITLE
Aarch64 image of immich-microservices

### ISSUE THREAD

**Issue by Atemu** [alextran1502/immich#152]
immich-server has an aarch64 image and all the external images do too but immich-microservices doesn't.  

It'd be helpful to have an aarch64 image in order to be able to run Immich on an M1 mac natively.

**Comment by alextran1502** [comment]
I remember why I didn't have this, the build will fail when trying to run NPM install on the image since it is the same issue that Tensorflow doesn't have support for arm64 yet.

Please take a look at this issue from [Tensorflow Repo](https://github.com/tensorflow/tfjs/issues/5937)
