### ISSUE TITLE
[BUG] Object detection pipeline not running

### ISSUE THREAD

**Issue by Eidenz** [alextran1502/immich#156]
I was wondering how you implemented object detection. Does it run periodically, or is it supposed to be called after an image is uploaded?

It's barely mentioned in the readme, and I don't see any tags or calls in microservices logs for now (just started uploading some pics to test).

You mention it's based on COCO SSD, do you consider offering alternatives in the future?

**Comment by Eidenz** [comment]
Okay I see, thanks for the info.

But then I think my installation may have a problem. Because 0 detections on 200 pictures, and no logged attempt in the microservices..

**Comment by alextran1502** [comment]
Thank you for the info, I just tested and this is a bug.

**Comment by alextran1502** [comment]
The issue has been fixed now, it will be built with the `latest` tag on the Dockerhub shortly
