### ISSUE TITLE
[BUG] android press more time back button it goes to the login screen,

### ISSUE THREAD

**Issue by spupuz** [alextran1502/immich#175]
on android press more time back button it goes to the login screen, should go to the homepage in casae

**Comment by spupuz** [comment]
Can you solve this? Is pretty annoying, there should be a log off icon e and eventually the back button should not logoff but send to the home

**Comment by alextran1502** [comment]
Will put this in for hotfix release in the coming days

**Comment by alextran1502** [comment]
Fixed in #193

**Comment by spupuz** [comment]
if phone restarted opening the app it present the login screen.
