### ISSUE TITLE
Database hostname hardcoded

### ISSUE THREAD

**Issue by kiguigui** [alextran1502/immich#177]
Hello there,

at first: thank you for this great app!

But it seems that Immich Server has the hostname for Postgres hardcoded so it is mandatory to set container_name in docker-compose and not possible to use a standalone database server. 

Is it possible to define an additional ENV-Variable like Database_hostname to define the name of the database server? For Example: Database_hostname=mydatabase.my.domain

**Comment by alextran1502** [comment]
Hello the PR #174 is being worked on to work on this issue along with Redis instances :)

**Comment by spupuz** [comment]
yeah for this reason can't spin up a double istance from scratch, i just have just one server :)

**Comment by kiguigui** [comment]
Hey Alex,

ohh i didn't look in the pull requests. Well that sounds great, thank you for your quick reply :)

**Comment by alextran1502** [comment]
@kiguigui PR #174 has been merged, you can now set your own Redis instance as well as Postgres server.
