### ISSUE TITLE
can't backup

### ISSUE THREAD

**Issue by ippocratis** [alextran1502/immich#18]
```
proxy_nginx      | 192.168.1.7 - - [10/Feb/2022:13:05:52 +0000] "GET /server-info HTTP/1.1" 200 172 "-" "Dart/2.16 (dart:io)" "-"
proxy_nginx      | 192.168.1.7 - - [10/Feb/2022:13:05:54 +0000] "GET /asset/825a5b4cc4e8809d HTTP/1.1" 200 2 "-" "Dart/2.16 (dart:io)" "-"
proxy_nginx      | 2022/02/10 13:05:54 [warn] 23#23: *5 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 192.168.1.7, server: , request: "POST /asset/upload HTTP/1.1", host: "192.168.1.24:2283"
immich_server    | Error: EACCES: permission denied, mkdir './upload/d718b7a8-1b85-4604-ac76-a374f8447dd9/original/825a5b4cc4e8809d'
immich_server    |     at mkdirSync (node:fs:1336:3)
immich_server    |     at DiskStorage.destination [as getDestination] (/usr/src/app/src/config/multer-option.config.ts:28:18)
immich_server    |     at DiskStorage._handleFile (/usr/src/app/node_modules/multer/storage/disk.js:31:8)
immich_server    |     at /usr/src/app/node_modules/multer/lib/make-middleware.js:145:17
immich_server    |     at fileFilter (/usr/src/app/src/config/multer-option.config.ts:15:7)
immich_server    |     at wrappedFileFilter (/usr/src/app/node_modules/multer/index.js:44:7)
immich_server    |     at Busboy.<anonymous> (/usr/src/app/node_modules/multer/lib/make-middleware.js:115:7)
immich_server    |     at Busboy.emit (node:events:520:28)
immich_server    |     at Busboy.emit (/usr/src/app/node_modules/busboy/lib/main.js:38:33)
immich_server    |     at PartStream.<anonymous> (/usr/src/app/node_modules/busboy/lib/types/multipart.js:213:13)
proxy_nginx      | 2022/02/10 13:05:55 [error] 23#23: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.7, server: , request: "POST /asset/upload HTTP/1.1", upstream: "http://xxx.xx.x.x:3000/asset/upload", host: "192.168.1.24:2283"
proxy_nginx      | 192.168.1.7 - - [10/Feb/2022:13:05:55 +0000] "POST /asset/upload HTTP/1.1" 502 157 "-" "-" "-"
```

i chmod -R 755 ~/immich/sever/upload

```
proxy_nginx      | 2022/02/10 13:14:36 [error] 22#22: *25 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.7, server: , request: "POST /asset/upload HTTP/1.1", upstream: "http://xxx.xx.x.x:3000/asset/upload", host: "192.168.1.24:2283"
proxy_nginx      | 192.168.1.7 - - [10/Feb/2022:13:14:36 +0000] "POST /asset/upload HTTP/1.1" 502 157 "-" "-" "-"
```

**Comment by alextran1502** [comment]
This is from a RaspberryPi 400, correct? In the Nginx message, did you masked the server address as xxx.xx.x.x?

**Comment by alextran1502** [comment]
Can you try 

'sudo chown -R yourusername:yourusername ~/immich/server/upload'

**Comment by ippocratis** [comment]
> This is from a RaspberryPi 400, correct? In the Nginx message, did you masked the server address as xxx.xx.x.x?

from the raspberry pi400 yes
i just replaced the actual adress with xxx for this post

**Comment by alextran1502** [comment]
The file won't be copied to your local `immich/server/upload`. You can see it in the container shell or in the `/var/lib/docker/volumes/` where it is mounted. 

Did you build the mobile directly or use the APK? If you use the APK, please try a different APK here. 
https://github.com/alextran1502/immich/suites/5244393557/artifacts/161419112

From the root of the directory `immich` can you run `make dev-update`?

**Comment by alextran1502** [comment]
No worry, I think you are very close. Unfortunately, I don't have the pi400 to try this on, otherwise, I can help you with better information. 

Let me know how it goes!

**Comment by ippocratis** [comment]
came upon this
https://github.com/nodejs/docker-node/issues/1262#issuecomment-677577653

i tried to build with 
```COPY --chown=node:node``` in the copy commands
acording to [this](https://github.com/nodejs/docker-node/issues/1262#issuecomment-677577653)
also tried with
```RUN npm install  --unsafe-perm=true```
acording to [this](https://stackoverflow.com/a/49085422)
still ```Error: EACCES: permission denied```

**Comment by alextran1502** [comment]
Can you clone the repo to the new location, in server folder you create the upload directory first. Then you run the docker compose up command?

**Comment by alextran1502** [comment]
@ippocratis I want to let you know that I can replicate your problem and is working on the fix.

**Comment by alextran1502** [comment]
@ippocratis I updated the docker-compose file. I was always running my development environment as root so I didn't encounter the problem when using volume mount, once I switch to a non-root user, then I have that issue. The solution I came up with is to use volume mount and let the user specify where they want to store all of the access on their local machine in the `UPLOAD_LOCATION` key in `.env` file.

Let's say you create a directory `~/my-immich-asset` then you would put `home/your-user-name/my-immich-asset` to `UPLOAD_LOCATION`. This will help with the access permission. Let me know if you can get it working!

**Comment by ippocratis** [comment]
yep working fine now
you are a hero 
thanks
