### ISSUE TITLE
[QUESTION] Why not use Flutter web?

### ISSUE THREAD

**Issue by xpwmaosldk** [alextran1502/immich#181]
Hi
Thanks for making the awesome app.
I will use this for my family.
I am so excited and want to contribute to this project in various ways.
But in my opinion the technology stack for this project is too diverse.
Besides, this project has recently made a web with Svelte.
You have Flutter skills, so why did you choose Svelte?
What do you think about integrating web and app with Flutter?

**Comment by spupuz** [comment]
flutter should be probably a more flexible solution

**Comment by xpwmaosldk** [comment]
I agree. @alextran1502 
I'm always rooting for you
And I'll look for the parts that I can contribute to this project.
Thank you

**Comment by alextran1502** [comment]
@xpwmaosldk Thank you for the kind words. I am really happy that this application is not inly helping me and my family but yours as well!
