### ISSUE TITLE
[Question] Does immich share common image between user

### ISSUE THREAD

**Issue by Nonobis** [alextran1502/immich#183]
Hello :)

 I have started to backup my mife and mine picture via immich but i see a folder by user uuid in server ...
If we have duplicate picture between account how do you manage this ? Keep duplicate or not ?

**Comment by alextran1502** [comment]
I assume you guys share the same account? 

Regardless, from each device, the file that is backup is unique by device, even if you guys have the same picture, it would show as two different photos/videos

**Comment by Nonobis** [comment]
No, like in google photos, we have 2 distincts accourt but in Google Photos, we have a full permanent share of photos ... so we have pictures duplicated between the 2 account ...

**Comment by alextran1502** [comment]
This should be the same situation on Immich since the photos are unique for each device, there is no mechanism of deduplication of similar photos in the application (at least not yet)
