### ISSUE TITLE
immich-microservices Container pinning CPU at 100%

### ISSUE THREAD

**Issue by darrylgibbs** [alextran1502/immich#210]
**Describe the bug**
After backing up all photos from my phone, the Microservices container runs at 100% CPU.  RAM usage is negligible. The photo library is only 34 images, and the CPU is still pinned 14 hours after initial sync.

**Task List**
Running in a VM on Proxmox, one of many other docker apps running.  Photos are synced to a directory on my NAS (seperate device).  CPU is a Interl J4205 (4 cores) and 6GB RAM has been allocated.

**To Reproduce**
Unknown

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS + Docker

**Comment by alextran1502** [comment]
Can you try restarting the application to see if it resolves the problem? I haven't experienced this issue yet

**Comment by alextran1502** [comment]
Can you also provide your phone model and which type of assets did you upload to Immich? might be a special case that I haven't thought out yet?

**Comment by darrylgibbs** [comment]
![Screenshot 2022-06-10 091747](https://user-images.githubusercontent.com/9167471/173062585-038e372b-da01-4cf8-b4ca-09b39ba1e29e.png)

The CPU usage % jumps rapidly between 100 and 195% constantly, even after restart. I even went as far as deleting the app from my phone, but this continues.

I have a Samsung S8 International model.  Photos and H265 video files, directly from the camera folder.

**Comment by darrylgibbs** [comment]
@alextran1502 I did restart the server, all the containers in fact.  The results were the same.

I'll restart them now, and leave them for an hour or so and check in on the CPU usage again.  That should be a good enough test?

**Comment by alextran1502** [comment]
yes, thank you.

When the container running with the spike, I assume you didn't perform any backup, correct?

**Comment by darrylgibbs** [comment]
@alextran1502 correct.  I've take no new photos since before first booting up these containers, so there has been nothing new to add.

**Comment by alextran1502** [comment]
Thank you for the info

**Comment by darrylgibbs** [comment]
An hour later, usage still high across all 4 cores.

**Comment by alextran1502** [comment]
Can I assume this is only happen in the VM with other dockers container running? And it wouldn't behave this way if you create a new VM and run Immich on that one? 

If this issue only persists in the VM with multiple containers, you can limit the CPU usage of that specific container in the docker compose file

https://stackoverflow.com/questions/59657728/set-cpu-limit-in-docker-compose

**Comment by darrylgibbs** [comment]
Yes it's one of my docker containers. I will need to create a new VM and try.

I didn't know that I could limit CPU usage. That's petty cool.  Although, I had imagined that the usage would spin down when there is nothing to do.  I didn't expect that this would be hitting the CPU continuously.  Is that normal behaviour?

**Comment by alextran1502** [comment]
No that is not normal behavior. CPU should stay at around 1-2% when there is no image being uploaded to the server. I haven't seen this behavior before so it is strange, I guess it might have to do something with the specific VM you are running the containers.

Below is my production setup of Immich, when there is no operating on the server.

<img width="952" alt="Screen Shot 2022-06-10 at 14 12 15" src="https://user-images.githubusercontent.com/27055614/173134421-593f7333-2daf-4318-aa48-44f479321741.png">

**Comment by alextran1502** [comment]
Hello, did you have a chance to test on a different VM?

**Comment by Leberkassemml** [comment]
For me, when i restart my server (Openmediavault) immich_postgres does not start and an service in the stack produces a high CPU load. Once i restart immich_postgres maually, everything works fine.

Maybe that's the same problem OP has?

Note that i don't have the latest docker image yet, i use portainer and have immich-machine-learning deactivated.

**Comment by darrylgibbs** [comment]
Sorry for the massive delay.

So I fired up a new VM, and install immich (using the new container layout I see) and I still have the same issue, although now it's the MACHINE LEARNING container and not MICROSERVICES.  These containers have been up for about an hour at the time of the screenshot, and with about 30 images on the server.  The VM has 2cores and 2GB RAM, same host HW if that makes any difference.
![Screenshot 2022-06-16 093357](https://user-images.githubusercontent.com/9167471/174070911-62dc9291-dbe4-41c9-b885-1cf2c2c731f4.png)

**Comment by darrylgibbs** [comment]
@alextran1502 This was a different VM, but on the same Proxmox host.

**Comment by alextran1502** [comment]
@darrylgibbs so probably somethings with that container cannot run on your machine. Is there anything strange you able to observe from the log of that container?

**Comment by darrylgibbs** [comment]
Other than this, no:

```
today at 8:59:54 PMIllegal instruction (core dumped)
today at 9:00:00 PM
today at 9:00:00 PM> nest_microservices@0.0.1 prebuild
today at 9:00:00 PM> rimraf dist
today at 9:00:00 PM
today at 9:00:01 PM
today at 9:00:01 PM> nest_microservices@0.0.1 build
today at 9:00:01 PM> nest build
today at 9:00:01 PM
```

What function will I loose without that container? Object recognition?

**Comment by alextran1502** [comment]
@darrylgibbs ohhh the container is not event starting up! It keeps restarting so that is why the CPU usage is high. You mentioned that you are using Promox right? Have you tried setting the CPU to host? Refer to the last section in Readme!

**Comment by darrylgibbs** [comment]
Ah man, I forgot about that! Previously I used Immich on my Pi4, and that wasn't a concern for me then, and then I forgot about it.

It seems my CPU doesn't support AVX/AVX2 which is SUCH A BUMMER!!!  Sorry for wasting your time instead of RTMF!

Either way, fantastic project you have here, and I'll use it regardless!
