### ISSUE TITLE
[Feature]: Add `logout/sign out` button for web GUI

### ISSUE THREAD

**Issue by BackedUpBooty** [alextran1502/immich#214]
### Feature detail

If I'm being super dumb and not finding it then apologies, and please explain where the logout button is. I can find it on the android app, but not the web gui. 

Otherwise... please add a logout/sign out button to the web gui. 

### Platform

Web

**Comment by alextran1502** [comment]
Yep, there is no button for singing out yet.

**Comment by alextran1502** [comment]
You can now signout by clicking on the user profile icon and then press sign out

<img width="422" alt="Screen Shot 2022-06-11 at 23 11 43" src="https://user-images.githubusercontent.com/27055614/173214120-853396c2-ecd5-4b16-b05f-aea715b3e9b8.png">

**Comment by BackedUpBooty** [comment]
Hi Alex, that's great, thank you very much!
