### ISSUE TITLE
[BUG] Trouble setting up on Rpi4

### ISSUE THREAD

**Issue by dashielllubsen** [alextran1502/immich#229]
**My Setup**
I have a raspberry pi 4 8gb running on raspi os buster and I'm trying to install immich on docker.

**Describe the bug**
When I install Immich on my raspberry 4 in docker, I get a fatal error that does not allow the server to be accessible.

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [X] If my setup is different, I have included my docker-compose file.
- [X] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
Follow the installation instructions by using the env file and the docker-compose file. Then you will have the error.

**Expected behavior**
What I expected to happen was for me to be able to use the server and set it up for the first time.

**Screenshots**
<img width="1033" alt="Screen Shot 2022-06-18 at 3 16 44 PM" src="https://user-images.githubusercontent.com/67878421/174453237-197c9125-718d-40bc-9485-2fab903a058a.png">

**Desktop (please complete the following information):**
 - OS: Raspi Os Buster

**LOGS**

**immich_machine_learning**
<img width="994" alt="Screen Shot 2022-06-18 at 3 18 49 PM" src="https://user-images.githubusercontent.com/67878421/174453289-50accfad-2684-4a53-aa81-290987fffa35.png">

**immich_microservices**
<img width="663" alt="Screen Shot 2022-06-18 at 3 19 41 PM" src="https://user-images.githubusercontent.com/67878421/174453320-fc32bc17-391e-46c4-a5af-da1ec4c922b2.png">

**immich_server**
<img width="367" alt="Screen Shot 2022-06-18 at 3 20 08 PM" src="https://user-images.githubusercontent.com/67878421/174453527-ed4a6e44-0ce9-4efc-9a49-058254ca5693.png">

**immich_web**
<img width="460" alt="Screen Shot 2022-06-18 at 3 20 38 PM" src="https://user-images.githubusercontent.com/67878421/174453776-16a12cce-b3cb-48fc-ae35-2c9cc0128f09.png">

**immich_postgres**
<img width="1131" alt="Screen Shot 2022-06-18 at 3 21 03 PM" src="https://user-images.githubusercontent.com/67878421/174453996-c3e38fe4-9efc-445f-9485-a05e7cb67dd4.png">

**immich_redis**
<img width="745" alt="Screen Shot 2022-06-18 at 3 21 39 PM" src="https://user-images.githubusercontent.com/67878421/174454291-b382a933-141c-4909-be81-c342a8551eb0.png">

**DOCKER_COMPOSE FILE**
[docker-compose.txt](https://github.com/alextran1502/immich/files/8934231/docker-compose.txt)
_I renamed this file to txt to be able to upload. It is usually docker_compose.yml_

**.env file**
[env.txt](https://github.com/alextran1502/immich/files/8934234/env.txt)
_I renamed this file to txt to be able to upload. It is usually .env_

**Comment by alextran1502** [comment]
Can you try to run the application  from the command line, without using Portainer first? 

From what it looks like, this seems like Docker problem on your machine

**Comment by EnricoBilla** [comment]
Hi, I used your docker-compose and your .env on a Pi4 4GB but everything is working as expected. 
Do you have anything else running in docker?

**Comment by zackpollard** [comment]
The postgres logs make it seem like your raspberry pi's local clock isn't set which could cause a whole bunch of problems. Can you run the `date` command on the terminal and post the output here?

**Comment by dashielllubsen** [comment]
> as

Yes, I do. I have homeassistant.

**Comment by dashielllubsen** [comment]
> Do you have anything else running in docker?

Yes, I do. I have homeassistant supervised.

**Comment by dashielllubsen** [comment]
> Can you try to run the application from the command line, without using Portainer first?

When I originally installed it, I stored my docker-compose file in /immich and stored my .env file in /var/lib/docker. Are those the right places to store my files? I just want to make sure that isn't causing it. Thank you!

**Comment by dashielllubsen** [comment]
> The postgres logs make it seem like your raspberry pi's local clock isn't set which could cause a whole bunch of problems. Can you run the `date` command on the terminal and post the output here?

I have fixed my date and time and still are getting the errors in the server which make this unusable.

**Comment by alextran1502** [comment]
@dashielllubsen the `.env` file should be in the same directory where the docker-compose file is at. Additionally, there is a Nginx configuration file that the docker-compose file is looking for as well

**Comment by dashielllubsen** [comment]
> the `.env` file should be in the same directory where the docker-compose file is at. Additionally, there is a Nginx configuration file that the docker-compose file is looking for as well

My env file is in the same directory as my docker-compose file. By Nginx config file, do you mean the settings folder that the nginx container generates in the same directory as my docker-compose file and my env file? Thanks

**Comment by alextran1502** [comment]
@dashielllubsen Yes, it is correct. As you can see in the docker-compose file, the Nginx config file is mapped to the config folder in the `docker` directory of the repo.

**Comment by dashielllubsen** [comment]
> Yes, it is correct. As you can see in the docker-compose file, the Nginx config file is mapped to the config folder in the `docker` directory of the repo.

Hi. I have tried so hard to get this to work. I even removed everything and recreated the config files, but I keep getting the same errors. What should I do?

**Comment by dashielllubsen** [comment]
> @dashielllubsen Yes, it is correct. As you can see in the docker-compose file, the Nginx config file is mapped to the config folder in the `docker` directory of the repo.

I am just getting trace/breakpoint trap, core dumped. Does it have anything to do with the tensorflow build issue?

**Comment by dashielllubsen** [comment]
> Would it be possible for you to make a new image for your rpi4 on the sd card? Starting from clean state if the machine?

Yes, I could definetely do that. I will let you know once I have formatted it.

**Comment by alextran1502** [comment]
There is a new release we've just pushed out 

https://github.com/alextran1502/immich/releases/tag/v1.13.0_20-dev 

This release includes the changes in the docker-compose file to fix a vulnerability related to PostgreSQL and also fix the issue with CORS. This perhaps helps fix the issue you are facing as well. Please take a look at the release file as well as the readme file for setup instruction

**Comment by alextran1502** [comment]
@dashielllubsen I saw that you have opened a features request, I assume after reformatting the SD Card, you are able to run Immich?

**Comment by m4rkv5** [comment]
To confirm that the image is ok, I did a fresh install with version 1.13.0 on Rpi4 and everything seems to work (except disabled machine learning).

Raspberry Pi 4 Model B Rev 1.4
Debian GNU/Linux 11 (bullseye) aarch64 
Kernel: 5.15.32-v8+
