### ISSUE TITLE
[BUG] Getting TypeError in immich-server when viewing large media files in web interface

### ISSUE THREAD

**Issue by simonliu99** [alextran1502/immich#230]
**Describe the bug**
Large video upload works after latest release but logs show errors. Video also does not play in web interface but has thumbnail.
```
immich-server_4            | [Nest] 29  - 06/19/2022, 12:47:34 AM   ERROR Error serving VIDEO asset
immich-server_4            | [Nest] 29  - 06/19/2022, 12:47:34 AM   ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
immich-server_3            | [Nest] 29  - 06/19/2022, 12:47:35 AM   ERROR Error serving VIDEO asset
immich-server_3            | [Nest] 29  - 06/19/2022, 12:47:35 AM   ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
immich-server_2            | [Nest] 29  - 06/19/2022, 12:47:39 AM   ERROR Error serving VIDEO asset
immich-server_2            | [Nest] 29  - 06/19/2022, 12:47:39 AM   ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
immich-server_4            | [Nest] 29  - 06/19/2022, 12:47:39 AM   ERROR Error serving VIDEO asset
immich-server_4            | [Nest] 29  - 06/19/2022, 12:47:39 AM   ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
```

**To Reproduce**
1. Same video in #54 
2. Upload to server
3. Observe TypeError in logs when trying to view in web interface

**Expected behavior**
Video should play without TypeError in web interface.

**Desktop (please complete the following information):**
 - OS: iOS (client), Windows 11 (server)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: iOS 15.5

**Comment by alextran1502** [comment]
I guess that video is in the queue to be converted to MP4 (iOS video is MOV and cannot be played on the browser T_T) and it wasn't converted yet when you were trying to play it. Can you check again?

If you uploaded the video a while back and the player on the web cannot play it, do you have a PostgreSQL client to access the database to check for further troubleshooting?

**Comment by simonliu99** [comment]
You're right, it does like it loads and plays back fine once it's been processed through the mp4 converter.
