### ISSUE TITLE
[BUG] Cannot get user creation screen on IP:2885 - Error 500

### ISSUE THREAD

**Issue by mineketchup** [alextran1502/immich#251]
**Describe the bug**
I get Error 500 when accessing IP:2885 and I'm not able to create a user
I'm trying to set up this docker on a Raspberry Pi 4 8GB model and I'm failing. I didn't have issues on old versions like 1.7 (when there was no web interface)

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [x] If my setup is different, I have included my docker-compose file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**Configuration**
Hardware: Raspberry Pi 4 8GB
OS: Ubuntu Server 20.04 64bit

**To Reproduce**
1. I get through wget the zip file of version 1.12.0 of this project. Then copy what's inside to ~/Documents/Immich
2. Then I create a .env file from .env.example and edit the text. 
3. Then i edit the docker-compose.yml and comment the lines related to immich-microservice and tensorflow (since I'm using a Raspberry which is not supported)
4. Then I run the command listed on Readme to start the server
5. In the end I try to connect to IP:2885 when I see that the console says 

> "immich-web_1     | Listening on 0.0.0.0:3000"

6. But instead of getting the web user creation screen I get the following error on the browser:

>500
>request to http://192.168.11.2:2883/user/count failed, reason: connect ETIMEDOUT 192.168.11.2:2883
>FetchError: request to http://192.168.11.2:2883/user/count failed, reason: connect ETIMEDOUT 192.168.11.2:2883

7. On the console the error looks like this:
>immich-web_1     | FetchError: request to http://192.168.11.2:2883/user/count failed, reason: connect ETIMEDOUT 192.168.11.2:2883
>immich-web_1     |     at ClientRequest.<anonymous> (file:///usr/src/app/build/shims-eb608bdd.js:6246:11)
>immich-web_1     |     at ClientRequest.emit (node:events:527:28)
>immich-web_1     |     at Socket.socketErrorListener (node:_http_client:454:9)
>immich-web_1     |     at Socket.emit (node:events:527:28)
>immich-web_1     |     at emitErrorNT (node:internal/streams/destroy:157:8)
>immich-web_1     |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>immich-web_1     |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Expected behavior**
I should get the web user creation screen

**Other**
1. I tried to look on the issues page but they generally seemed to have errors related to how they edited the docker-compose.yml so I tried to leave the most possible as default
2. In addition if I try to access IP:2883/server-info/ping, /user/count they give the response as intended; also IP:2885/admin redirects to /auth/login and it shows the login page
3. This is the nginx log in case it helps:
>proxy_nginx      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
>proxy_nginx      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
>proxy_nginx      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
>proxy_nginx      | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
>proxy_nginx      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
>proxy_nginx      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
>proxy_nginx      | /docker-entrypoint.sh: Configuration complete; ready for start up
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: using the "epoll" event method
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: nginx/1.23.0
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: OS: Linux 5.4.0-1065-raspi
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: start worker processes
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: start worker process 22
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: start worker process 23
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: start worker process 24
>proxy_nginx      | 2022/06/23 09:38:35 [notice] 1#1: start worker process 25

I don't know if _**"/etc/nginx/conf.d/default.conf is not a file or does not exist"**_ should be considered. Others had this but you didin't seem to point out

**Screenshots**
![Screenshot from 2022-06-23 11-36-20](https://user-images.githubusercontent.com/107675515/175269069-deddf598-8f89-4ffa-bb04-732ebcbfed31.png)

**docker-compose.yml**
[docker-compose.txt](https://github.com/alextran1502/immich/files/8966087/docker-compose.txt)

**.env**
[env.txt](https://github.com/alextran1502/immich/files/8966076/env.txt)

**Comment by alextran1502** [comment]
For your VITE_SERVER_ENDPOINT can you try http instead of https?

**Comment by alextran1502** [comment]
Also with the latest version you should only commented out the immich-machine-learning. You will need immich-microservice for the core functionalities

**Comment by mineketchup** [comment]
> For your VITE_SERVER_ENDPOINT can you try http instead of https?

Oh sorry, I mistakenly uploaded the old .env file. In fact the old one was giving me the same error but with https://192.168.11.2:2558/ 
Changing it to http didn't solve anything so I created this report

>Also with the latest version you should only commented out the immich-machine-learning. You will need immich-microservice for the core functionalities

I'll try that later when I get back to home, but I first encountered the same error when I had them without commenting out so I don't think it will solve the problem.

Anyway, appreciate your help, we'll see later.

**Comment by alextran1502** [comment]
Another thing you should check is to allow on Firewall UFW port 2283 and
2285

**Comment by mineketchup** [comment]
1. So I updated docker-compose to the latest version available (2.6.1) from the releases pages of their github page and tried to run by removing the comments from immich_microservices and i still get the same error:

>docker-immich-web-1            | FetchError: request to http://192.168.11.2:2883/user/count failed, reason: connect ETIMEDOUT 192.168.11.2:2883
docker-immich-web-1            |     at ClientRequest.<anonymous> (file:///usr/src/app/build/shims-eb608bdd.js:6246:11)
docker-immich-web-1            |     at ClientRequest.emit (node:events:527:28)
docker-immich-web-1            |     at Socket.socketErrorListener (node:_http_client:454:9)
docker-immich-web-1            |     at Socket.emit (node:events:527:28)
docker-immich-web-1            |     at emitErrorNT (node:internal/streams/destroy:157:8)
docker-immich-web-1            |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
docker-immich-web-1            |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

2. Running `sudo ufw status` gives me for ports 2882 and 2885:
>Status: active
>To                         Action      From
>--                         ------      ----
>2283                       ALLOW       Anywhere
>2285                       ALLOW       Anywhere
>2283 (v6)                  ALLOW       Anywhere (v6)
>2285 (v6)                  ALLOW       Anywhere (v6)

3. I don't know if it's relevant, but hen I try to connect to IP:2883 when it's in the process of creating the containers the console gives me the following response:
>proxy_nginx                    | 2022/06/24 00:33:52 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.11.14, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.6:3000/", host: "192.168.11.2:2283"

4. And I have a strange thing about time: when I run  `date` my system gives:
>Fri Jun 24 09:39:01 JST 2022

But if I `docker exec -it CONTAINER_ID sh` and then `date` it gives me:
>Fri Jun 24 00:40:56 UTC 2022

Basically the system one is correct. I'm trying to synchronize the docker time, but struggling to find the correct command so I'll give an update later when I'll succeed

**Comment by mineketchup** [comment]
So I was able to use the correct time zone inside docker by specifying:
>volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

So it uses the same time as the host, but it doesn't seem to resolve anything

**Comment by alextran1502** [comment]
I just got a Pi4 today, let me spin up one and try then I will get back to you

**Comment by mineketchup** [comment]
> I just got a Pi4 today, let me spin up one and try then I will get back to you

That's nice to hear, thank you!

In the meanwhile:
1. As a test, I started Immich from the old immich-1.9.0_13-dev and created a user by sending the command ` curl --location --request POST 'http://192.168.11.2:2283/auth/signUp' \` and it was successiful. 
2. Then I stopped the containers and restarted Immich but this time with the immich-1.12.0_18_dev
3. Then I opened the app and tried to login with credentials and pointing to http://192.168.11.2:2283 as Server Endpoint URL
4. The login was successiful. Even the IP:2283/user/count gives me :1.
5. But then I tried to login by accessing http://192.168.11.2:2285/auth/login and by pressing Enter and even tho the browser asked if I wanted to save the password, the web page was totally silent, like it was static.
6. So I tried to login by pressing the blue Login button but it seemed to be, again, totally silent

In the end I checked the browser console by pressing F12, and this is what I got

> Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
>--------
>r http://192.168.11.2:2285/_app/pages/auth/login/index.svelte-d2637f15.js:1
    InterpretGeneratorResume self-hosted:1422
    AsyncFunctionThrow self-hosted:636
    (Async: async)
    ee http://192.168.11.2:2285/_app/chunks/index-59c0653f.js:1


So... it seems the javascript releated files are not working? Because even the docker console error that I get when accessing IP:2885:

> docker-immich-web-1            | FetchError: request to http://192.168.11.2:2883/auth/login failed, reason: connect ETIMEDOUT 192.168.11.2:2883
docker-immich-web-1            |     at ClientRequest.<anonymous> (file:///usr/src/app/build/**shims-eb608bdd.js**:6246:11)

seems to suggest that is js releated
​

**Comment by alextran1502** [comment]
There is a new release we've just pushed out 

https://github.com/alextran1502/immich/releases/tag/v1.13.0_20-dev 

This release includes the changes in the docker-compose file to fix a vulnerability related to PostgreSQL and also fix the issue with CORS. This perhaps helps fix the issue you are facing as well. Please take a look at the release file as well as the readme file for setup instruction

**Comment by mineketchup** [comment]
Maaaan, we were absolutely blind.....
I've put IP:2883 insted of IP:2283 in the .env file....... and I was continuing to do the same error for every new instance and configuration....
Now it works..... I'm really sorry for this stupid mistake and wasting of your time

**Comment by alextran1502** [comment]
@mineketchup  Ah, no worry. By the way, there is a new release and setup, the changes are noted in the release note.

**Comment by mineketchup** [comment]
> @mineketchup Ah, no worry. By the way, there is a new release and setup, the changes are noted in the release note.

Everything works as expected. Thank you for this awesome product!
