### ISSUE TITLE
Clear Instructions

### ISSUE THREAD

**Issue by athornfam2** [alextran1502/immich#255]
The question option looks to be gone when submitting an issue... 

Hoping the maintainer or others could answer.. What are the steps/procedures to to install all the requirements and operate the application on a Ubuntu VM?

**Comment by zackpollard** [comment]
There are instructions to setup the application in the README file on the repo using docker-compose. Please try to follow those instructions then file an issue if you can't get it working with those steps or join the discord to get help from us or the community.
