### ISSUE TITLE
[Feature]: Add directory of local photos on external disk to immich

### ISSUE THREAD

**Issue by dashielllubsen** [alextran1502/immich#258]
### Feature detail

Is there any way to import a already created directory into immich? My photos are already stored on an external drive and  I have hundreds of GB’s on that drive worth in photos.

It would be great to be able to use Immich on my devices to access these photos. 
If not, could you consider this as a feature to a add? 

thank you!!

### Platform

Server

**Comment by alextran1502** [comment]
There is currently no plan for this feature. It is one of the most requested features. I and the team will consider this.

**Comment by alextran1502** [comment]
Duplicate #7
