### ISSUE TITLE
[BUG] start docker-compose and shows that unable to connect to the database 

### ISSUE THREAD

**Issue by rmGFW** [alextran1502/immich#269]
How to repetition :
1 . pull the main branch 
2.  cd docker && cp .env.test .env 
3. docker-compose up 

![image](https://user-images.githubusercontent.com/66858140/175861212-bd60c6ad-ca2d-4e2b-9bb4-587310dd652d.png)

**Comment by zackpollard** [comment]
I'm going to close this due to lack of information, if you still require help please file another issue with the request information, or find us on discord here https://discord.gg/Umwg7JSh and we'll be happy to help! 😄
