### ISSUE TITLE
[BUG] issue with latest App Store build

### ISSUE THREAD

**Issue by athornfam2** [alextran1502/immich#299]
**Describe the bug**

**To Reproduce**
1. Update to the latest Immich app on iOS
2. Go to backups and it will get stuck backing up

**Expected behavior**
Typically this would backup directly to the Immich server before I updated the app 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 15

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 15
 - Version .5

**Additional context**
https://user-images.githubusercontent.com/74559383/177078533-97936d1d-f1e7-4072-9047-81cb132729ca.MOV

**Comment by alextran1502** [comment]
What is your server and app version? 

You can check it from the upper left top icon from the mobile app

**Comment by athornfam2** [comment]
1.16.0 & 1.16.0 build 27

**Comment by alextran1502** [comment]
Can you try to restart the server as well as to reinstall the app?

**Comment by alextran1502** [comment]
Did you perform `docker-compose pull` to update the containers?

**Comment by alextran1502** [comment]
There is a user reported facing this issue as well, somehow the key in the database get conflicted and cannot record that newly updated asset. 

I will come back with a fix

**Comment by alextran1502** [comment]
@athornfam2 for some context, can you show the album that you selected for upload?

**Comment by athornfam2** [comment]
Looks to be Recents (All), Recents (All

**Comment by athornfam2** [comment]
Performed a server restart and also performed a docker compose pull too... for information

**Comment by alextran1502** [comment]
> Looks to be Recents (All), Recents (All

@athornfam2 So it looks to be a bug in the album selector. Can you make sure that only 1 `Recents(All)` to be selected

**Comment by athornfam2** [comment]
It looks like it fixed itself on the recent iOS app update and docker update.
