### ISSUE TITLE
[BUG] Cannot edit existing users

### ISSUE THREAD

**Issue by athornfam2** [alextran1502/immich#302]
**Describe the bug**
Under Immich Administration I am unable to "Pencil" the user to edit any information.

**Task List**
- [x ] I have read thoroughly the README setup and installation instructions.
- [x ] If my setup is different, I have included my docker-compose file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Log into http://xxx.xxx.xxx.xxx:2283/api
2. Click on Administration
3. Create a new user if one does not exist
4. Attempt to click on the pencil next to the user/member

**Expected behavior**
I expect to be able to edit the user details (Name, e-mail, password, and any future information)

**Screenshots**
None

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
N/A

**Additional context**
Already on the latest docker repo and rebooted the server today - 7/4

**Comment by alextran1502** [comment]
Duplicated #220
