### ISSUE TITLE
[BUG] User registration email format is not enforced in API

### ISSUE THREAD

**Issue by bo0tzz** [alextran1502/immich#314]
When registering a user and signing in, you are expected to enter an email address for the user. The various forms enforce that this should be an email address, but the backend API does not. With a (manual) request to the API, it is possible to create an account with an invalid email address. It is then impossible to log in with this user, as the login form enforces the email address format.
I see two possible solutions:

  a. Remove all email address validation, and allow using any username (my preference)
  b. Enforce the email address validation at the API layer

Either way, I would remove the validation from the login form specifically, to prevent any chance of a lockout.

**Comment by jbaez** [comment]
We've discussed this internally, and for the time being we are going to enforce email address for registering users 🙂.
There is a considerable amount of work for switching to username.
We will be adding email validation in the API.
