### ISSUE TITLE
[Feature]: MOTD message on login screen

### ISSUE THREAD

**Issue by bo0tzz** [alextran1502/immich#317]
### Feature detail

It would be nice to be able to configure an MOTD message that is displayed to users on the login screen. The specific use case I have in mind is when running a demo instance, to inform users of the login credentials to use and the fact that the instance is reset regularly. It would also be useful on an instance that is used by multiple people, for the admin to inform them of scheduled downtime and such.

### Platform

Server

**Comment by zackpollard** [comment]
This was added in #329
