### ISSUE TITLE
[BUG] Empty mobile page when uploading from web only

### ISSUE THREAD

**Issue by Eidenz** [alextran1502/immich#331]
**Describe the bug**
I setup an immich instance and started uploading straight from the web version (about a hundred pics). However, when I open the android app to see my content, the page is empty.
I can see the pictures in the Search tab when I look for detected objects. But the main page is just blank.

I tried setting up another instance, same issue if you start uploading from web only. (I also tried reinstalling the android app)

**Task List**
- [X] I have read thoroughly the README setup and installation instructions.
- [x] If my setup is different, I have included my docker-compose file.
- [x] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Setup immich following the README steps
2. Start uploading from the web version only
3. Open the android app to see your uploaded content

**Expected behavior**
The web uploaded pictures shows up on the Android app.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 1.17.0_25-dev

**Smartphone (please complete the following information):**
 - Device: Mi 11
 - OS: CherishOS 3.9
 - Version: 1.17.0 build.25

**Comment by alextran1502** [comment]
Can you please include your `.env` and `docker-compose` files? They are in the requirement for troubleshooting purposes

**Comment by Eidenz** [comment]
Well the env and docker-compose are exactly the same from the repo, but here anyway:

[env.txt](https://github.com/alextran1502/immich/files/9084813/env.txt)
[docker-compose.txt](https://github.com/alextran1502/immich/files/9084823/docker-compose.txt)

**Comment by alextran1502** [comment]
I created a new instance with a fresh setup and the latest release version. However, I cannot reproduce this. Do you have a set of uploaded photos that you can share for testing?

**Comment by Eidenz** [comment]
Well it does this no matter what I feed it...

**Comment by Eidenz** [comment]
Nothing abnormal. Well, that's quite normal since I mentioned the web version works perfectly fine. The only problem is the blank page on the android version.
And I know it can actually retrieve the pictures since they show up in the Search tab..

I see nothing in logs either when I load up the app.

I forgot to mention I'm using the scaling option with `--scale immich-server=5`. It's the first time I try it (there will be thousands of pictures soon, so I prepared it).

**Comment by Eidenz** [comment]
Oh okay, I just read the `If you have a few thousand photos/videos, I suggest running docker-compose with scaling option for the immich_server` so I just went for it.

Well removing the scaling doesn't seem to fix it, but maybe I should try restarting fresh without scaling.

**Comment by alextran1502** [comment]
I am testing on Android. I think I might have found something. I will keep you updated.

**Comment by Eidenz** [comment]
Oh alright, will wait before another reinstallation then.

**Comment by alextran1502** [comment]
@Eidenz it was a permission issue on my end, not something with the application. So I cannot reproduce the issue :/. Can you try a new instance?

**Comment by Eidenz** [comment]
It worked. Re-doing the instance without scaling option fixed it, the pictures now appear on the android app.

**Comment by alextran1502** [comment]
OK, I will look into the scaling problem that presents a problem with uploading on the web

**Comment by Eidenz** [comment]
Actually, the pictures disappeared again after uploading all of the previous ones.

I didn't mention it as I didn't think it was important, but now it seems it might be a cause of the problem:

Some pictures show up as `Invalid date` in the immich web. I'm pretty sure as soon as I uploaded one of these invalid date pictures, they all disappeared from the android app.

**Comment by alextran1502** [comment]
Can you share some of the pictures that caused problem?

**Comment by Eidenz** [comment]
They are all very small MP4 videos (between 2 and 10sec). Here is one:

https://user-images.githubusercontent.com/27901016/178579094-32d4bcf1-cf82-449d-a880-d3227f68de94.mp4

**Comment by alextran1502** [comment]
Thanks, I can reproduce the issue now.
