### ISSUE TITLE
[Feature]: I create polish translate to Mobile App

### ISSUE THREAD

**Issue by vins345** [alextran1502/immich#349]
### Feature detail

Hi, i create polish translate for Mobile App.

1. How i can add this to new release?
2. Where another files to translate is located?

[pl-PL.zip](https://github.com/alextran1502/immich/files/9119331/pl-PL.zip)

### Platform

Mobile App

**Comment by alextran1502** [comment]
I will add the file to the source code. We use Localizely platform for the community to contribute to the translation. Please shoot me an email address you would like to use as well as the language(s) you would like to translate to and I will send out an invitation link

**Comment by vins345** [comment]
@alextran1502 b.ruk@visset.pl

**Comment by alextran1502** [comment]
Done, I also uploaded the file to the platform, feel free to add in any missing keys

**Comment by shirou93** [comment]
@alextran1502 hi. can i got invite to bartek04041993@gmail.com?
