### ISSUE TITLE
[BUG] <Backup from Android does not work>

### ISSUE THREAD

**Issue by MrColumbo** [alextran1502/immich#353]
**To Reproduce**
1. Go to '..Android App.'
2. Click on Backup and Select an Album
3. Start Backup
4. App is showing percentage is going up to 100% once for each photo but the circle (Backup in Progress) keeps spinning and no photos are uploaded to server

**Expected behavior**

I assume backup does upload photos to server and they will be visible there via app and web interface but they are not in my case

**Screenshots**
![photo_2022-07-16_14-21-06](https://user-images.githubusercontent.com/5223590/179359286-2f456d0c-40ed-4f2f-82cc-64ad5d7d2f31.jpg)

**Smartphone (please complete the following information):**
 - Device: One Plus 6T
 - OS: Android 11
 - Version latest Version ...it is EOL :(]

**Comment by bo0tzz** [comment]
Which version of the immich app and server are you on?

**Comment by MrColumbo** [comment]
App 1.14.0 build 21 and Server Version 1.18.0 (according to app) .....should be very recent since I just installed everything a couple of hours ago

**Comment by alextran1502** [comment]
@MrColumbo App newest version is v18

**Comment by MrColumbo** [comment]
it works well with 1.18 ;) 
.....what is the recommended way to get the app? There is note that the version on google play is always a bit behind due to the review process so I installed it from F-Droid but obviously it is more recent in google play.
Thanks for the quick support - highly appreciated!

**Comment by MrColumbo** [comment]
> @MrColumbo App newest version is v18. Where did you get the source?

F-Droid Appstore

**Comment by alextran1502** [comment]
@MrColumbo F-droid slower to update. Google Playstore should have the most recent version. Usually, it takes them 2 hrs to review and push out the new version. Apple AppStore takes them a few more hours, maybe half a day. The slowest to update is F-droid; take them a few days (up to 5)
