### ISSUE TITLE
Docker fails

### ISSUE THREAD

**Issue by geekedtv** [alextran1502/immich#51]
I really wanted this to work. It fails every time using docker.

```
npm WARN deprecated socket.io-redis@6.1.1: This package has been renamed to '@socket.io/redis-adapter', please see the migration guide here: https://socket.io/docs/v4/redis-adapter/#migrating-from-socketio-redis
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
```

**Comment by alextran1502** [comment]
Hello,

Can you please show me the full log message? And which operating system are you running on?

Can also you confirm that you've run the command below?

`docker-compose -f ./docker/docker-compose.yml up --build -V`

**Comment by alextran1502** [comment]
@geekedtv Do you have any update on this?

**Comment by ffidan61** [comment]
I got the same error here is the log:

> Building immich_server
Sending build context to Docker daemon  921.1kB
Step 1/8 : FROM node:16-alpine3.14 AS development
 ---> 61b24385412d
Step 2/8 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 7e4c97e5be92
Step 3/8 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 0d12dcab5684
Step 4/8 : COPY package.json package-lock.json ./
 ---> Using cache
 ---> 48eee65e6cc3
Step 5/8 : RUN apk add --update-cache build-base python3 libheif vips-dev vips ffmpeg
 ---> Using cache
 ---> 193e80027251
Step 6/8 : RUN npm install
 ---> Using cache
 ---> 0af961d58b89
Step 7/8 : COPY . .
 ---> Using cache
 ---> 83dc6a049be7
Step 8/8 : RUN npm run build
 ---> Using cache
 ---> a1459b1289b3
Successfully built a1459b1289b3
Successfully tagged immich-server-dev:1.0.0
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 348, in ensure_image_exists
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1948, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpht05b1ch'
[403965] Failed to execute script docker-compose

**Comment by alextran1502** [comment]
@ffidan61 can you open a new issue with more details of your system spec and the step you have taken?

Thanks

**Comment by alextran1502** [comment]
Please reopen if you still have the issue.
