### ISSUE TITLE
Android client disconnects when screen goes off

### ISSUE THREAD

**Issue by arminus** [alextran1502/immich#64]
Client: v.0.6 Android 8.0
Server: Pi4

Backup stops as soon as the screen of my device turns off/locks.

Server reports 
```
immich_server_1  | [Nest] 29  - 03/20/2022, 7:58:06 AM     LOG Client AEq3t1AYFKHKs2TeAAAN disconnected
```

I'd expect it to continue to run in the background?

When I turn on/unlock the device, backup will continue, there is the following message in the server's log:

```
immich_server_1  | [Nest] 29  - 03/20/2022, 7:49:00 AM   ERROR [ExceptionsHandler] The "path" argument must be of type string or an instance of Buffer or URL. Received null
immich_server_1  | TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received null
immich_server_1  |     at new ReadStream (node:internal/fs/streams:171:5)
immich_server_1  |     at createReadStream (node:fs:2873:10)
immich_server_1  |     at AssetService.serveFile (/usr/src/app/src/api-v1/asset/asset.service.ts:161:32)
immich_server_1  |     at runMicrotasks (<anonymous>)
immich_server_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
immich_server_1  |     at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
immich_server_1  |     at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

Backup continues for a while until the screen turns off again.

**Comment by alextran1502** [comment]
This is expected behavior for the current version. I have plans to work on background backup in future releases.

**Comment by alextran1502** [comment]
A potential package that solves this problem [flutter_uploader](https://github.com/fluttercommunity/flutter_uploader)

**Comment by LouisFaure** [comment]
Also, restricting backups to situations like battery charging and/or a non-metered wifi connection would be a must!

**Comment by ma-karai** [comment]
I'd already be happy, with a tick background upload enable at all costs. :D I'd upload my entire phone once when connected, and then untick that thing 🗡️ 

Btw: Alex, amazing work. I use immich with a photoprism, photolibre and photoview instance, and it just works perfectly.

**Comment by palitu** [comment]
@ma-karai  - what do you mean?  how do you do that?

**Comment by ma-karai** [comment]
How do I do what?

**Comment by spupuz** [comment]
Application logoff when is closed or the phone is restarted

**Comment by alextran1502** [comment]
@spupuz Let's open a new issue for that bug.

**Comment by spupuz** [comment]
> @spupuz Let's open a new issue for that bug.

I did

**Comment by alextran1502** [comment]
Closing this issue as it is the expected behavior for the app at this stage.
