### ISSUE TITLE
Server storage report is wrong for NFS mounted UPLOAD_LOCATION

### ISSUE THREAD

**Issue by arminus** [alextran1502/immich#66]
My target sync dir is an NFS mounted share, Immich reports free diskspace of the server host, not the actual UPLOAD_LOCATION. Basically, that could by anything, a fuse mounted S3, sftp, etc.

**Comment by alextran1502** [comment]
Good issue! I will look into this

**Comment by alextran1502** [comment]
This issue has been fixed in #72
