### ISSUE TITLE
[BUG] Docker-compose script execution failed

### ISSUE THREAD

**Issue by ffidan61** [alextran1502/immich#67]
**Describe the bug**
Can't spinn up an the immich docker container due to a docker-compose script execution error.

**To Reproduce**
Steps to reproduce the behavior/The way I tried to get immich to work:
1. git clone immich repo
3. cd into docker folder
4. edit .env
5. run docker-compose up -d

**Expected behavior**
Spinn up an immich docker container

**Desktop (please complete the following information):**
 - OS: Linux 5.4.0-104 Ubunutu x86_64
 - Docker version 20.10.11, build dea9396e18
 - Docker-compose version 1.29.2, build 5becea4c

**Additional context**

Docker build logs:
> Building immich_server
> Sending build context to Docker daemon  921.1kB
> Step 1/8 : FROM node:16-alpine3.14 AS development
>  ---> 61b24385412d
> Step 2/8 : ARG DEBIAN_FRONTEND=noninteractive
>  ---> Using cache
>  ---> 7e4c97e5be92
> Step 3/8 : WORKDIR /usr/src/app
>  ---> Using cache
>  ---> 0d12dcab5684
> Step 4/8 : COPY package.json package-lock.json ./
>  ---> Using cache
>  ---> 48eee65e6cc3
> Step 5/8 : RUN apk add --update-cache build-base python3 libheif vips-dev vips ffmpeg
>  ---> Using cache
>  ---> 193e80027251
> Step 6/8 : RUN npm install
>  ---> Using cache
>  ---> 0af961d58b89
> Step 7/8 : COPY . .
>  ---> Using cache
>  ---> 83dc6a049be7
> Step 8/8 : RUN npm run build
>  ---> Using cache
>  ---> a1459b1289b3
> Successfully built a1459b1289b3
> Successfully tagged immich-server-dev:1.0.0
> Traceback (most recent call last):
>   File "docker-compose", line 3, in <module>
>   File "compose/cli/main.py", line 81, in main
>   File "compose/cli/main.py", line 203, in perform_command
>   File "compose/metrics/decorator.py", line 18, in wrapper
>   File "compose/cli/main.py", line 1186, in up
>   File "compose/cli/main.py", line 1182, in up
>   File "compose/project.py", line 664, in up
>   File "compose/service.py", line 348, in ensure_image_exists
>   File "compose/service.py", line 1133, in build
>   File "compose/service.py", line 1948, in build
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmptan9biqs'
> [549391] Failed to execute script docker-compose

**Comment by alextran1502** [comment]
Can you try `docker-compose up --build -V` from the docker directory.

Did you change anything from the `docker-compose` file? Can you also share your `.env` file?

**Comment by ffidan61** [comment]
`docker-compose up --build -V` gave me this (same?) error:

> Building immich_server
Sending build context to Docker daemon  921.1kB
Step 1/8 : FROM node:16-alpine3.14 AS development
 ---> 61b24385412d
Step 2/8 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 7e4c97e5be92
Step 3/8 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 0d12dcab5684
Step 4/8 : COPY package.json package-lock.json ./
 ---> Using cache
 ---> 48eee65e6cc3
Step 5/8 : RUN apk add --update-cache build-base python3 libheif vips-dev vips ffmpeg
 ---> Using cache
 ---> 193e80027251
Step 6/8 : RUN npm install
 ---> Using cache
 ---> 0af961d58b89
Step 7/8 : COPY . .
 ---> Using cache
 ---> 83dc6a049be7
Step 8/8 : RUN npm run build
 ---> Using cache
 ---> a1459b1289b3
Successfully built a1459b1289b3
Successfully tagged immich-server-dev:1.0.0
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 348, in ensure_image_exists
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1948, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpql6mps1b'
[728260] Failed to execute script docker-compose

No I didn't touch the docker-compose file.
Here is my .env file

> # STAGE
> NODE_ENV=development
> 
> # Database
> DB_USERNAME=postgres
> DB_PASSWORD=postgres
> DB_DATABASE_NAME=immich
> 
> # Upload File Config
> UPLOAD_LOCATION=/home/furkan/media/pics
> 
> # JWT SECRET
> JWT_SECRET=29525AB6C77EB733BAFD38C898CA9AEB8FC0118F7D29A9A5F43F54457857F229
> 
> # MAPBOX
> ## ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
> ENABLE_MAPBOX=false
> MAPBOX_KEY=
>

**Comment by ippocratis** [comment]
Docker daemon is running?

`sudo systemctl start docker`

**Comment by alextran1502** [comment]
Found this similar issue on [StackOverflow](https://stackoverflow.com/questions/67986387/docker-compose-up-build-states-an-error-but-it-works-after-i-use-docker-compos)

Probably an issue from how you install docker, I assume you used `snap`?

**Comment by ffidan61** [comment]
At least not consciously I'll see if that's the reason.

**Comment by comfreak89** [comment]
Hi,

I tried 1.4.0-7-dev and a direct clone of the repository now. Same issue.

Direct clone:
```
root@docker:~/immich/immich# docker-compose -f ./docker/docker-compose.yml up --build -V
WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
Building immich_microservices
ERROR: forbidden path outside the build context: ../microservices/Dockerfile ()
```

1.4.0-7-dev:
```
root@docker:~/immich/immich-1.4.0-7-dev# docker-compose -f ./docker/docker-compose.yml up --build -V
WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
Building immich_microservices
ERROR: forbidden path outside the build context: ../microservices/Dockerfile ()
```

I am still corious why it says, that the variables in the .env are not set, althout it is available:

Direct clone:
```
root@docker:~/immich/immich# ls -la docker/.env
-rw-r--r-- 1 root root 376 Mar 30 14:13 docker/.env
root@docker:~/immich/immich-1.4.0-7-dev# cat docker/.env
# STAGE
NODE_ENV=development

# Database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=/mnt/data/Immich

# JWT SECRET
JWT_SECRET=ganXupoCQdV9rcTiM0DSxDmwP5vCB4UIfeUjhogzr1EpDloucvq2UAQd1bfk

# MAPBOX
## ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=
```

1.4.0-7-dev:
```
root@docker:~/immich/immich-1.4.0-7-dev# ls -la docker/.env
-rw-r--r-- 1 root root 376 Mar 30 14:12 docker/.env
root@docker:~/immich/immich# cat docker/.env
# STAGE
NODE_ENV=development

# Database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=/mnt/data/Immich

# JWT SECRET
JWT_SECRET=ganXupoCQdV9rcTiM0DSxDmwP5vCB4UIfeUjhogzr1EpDloucvq2UAQd1bfk

# MAPBOX
## ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=
```

No, I installed docker via apt. Snap is not available.

```
root@docker:~/immich/immich/docker# apt list --installed | grep docker

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker-ce-cli/focal,now 5:20.10.12~3-0~ubuntu-focal amd64 [installed,upgradable to: 5:20.10.14~3-0~ubuntu-focal]
docker-ce-rootless-extras/focal,now 5:20.10.12~3-0~ubuntu-focal amd64 [installed,upgradable to: 5:20.10.14~3-0~ubuntu-focal]
docker-ce/focal,now 5:20.10.12~3-0~ubuntu-focal amd64 [installed,upgradable to: 5:20.10.14~3-0~ubuntu-focal]
docker-compose/focal,now 1.25.0-1 all [installed]
docker-scan-plugin/focal,now 0.12.0~ubuntu-focal amd64 [installed,upgradable to: 0.17.0~ubuntu-focal]
python3-docker/focal,now 4.1.0-1 all [installed,automatic]
python3-dockerpty/focal,now 0.4.1-2 all [installed,automatic]
root@docker:~/immich/immich/docker# snap list

Command 'snap' not found, but can be installed with:

apt install snapd
```

In my case, the host is a LXC Container on the newest Proxmox Version.

root@docker:~/immich/immich/docker# lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
root@docker:~/immich/immich/docker# uname -r
5.13.19-4-pve
```
