### ISSUE TITLE
Constant high CPU load when idling

### ISSUE THREAD

**Issue by arminus** [alextran1502/immich#74]
Platform: Linux pi4 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
OS: Raspbian 11/bullseye

UPLOAD_LOCATION is an NFS filesystem, NODE_ENV=development

The docker node process from immich-server-dev:1.3.0 produces constant high CPU load:

![plot](https://user-images.githubusercontent.com/683680/160247515-aebcb76d-7276-4640-a34e-03884953bf7a.png)

Could this be node's watch mode? How do I turn this off?

**Comment by alextran1502** [comment]
You can try to replace the content in `server/entrypoint.sh` to
```
npm run build && npm run start:prod
```

let me know if this works and I will add make a `docker-compose` file for production.

**Comment by arminus** [comment]
Thanks, CPU usage is now normal.

**Comment by alextran1502** [comment]
Glad it helps, I will add this information into the readme.
