### ISSUE TITLE
[BUG] immich_microservices_1: Cannot find module '/usr/src/app/dist/main'

### ISSUE THREAD

**Issue by Mattyfaz** [alextran1502/immich#82]
**Describe the bug**
immich_microservices_1 fails with message: `Cannot find module '/usr/src/app/dist/main'`

**To Reproduce**
1. Clone repo
2. Run `docker-compose -f ./docker/docker-compose.yml up --build -V`
3. See error _(log attached)_

**Screenshots**
![Screen Shot 2022-03-29 at 12 27 56 pm](https://user-images.githubusercontent.com/10377148/160514131-ce0503c0-5f3c-4f43-87c8-da1df35ead22.png)

**Desktop (please complete the following information):**
 - OS: Debian 11

[log.txt](https://github.com/alextran1502/immich/files/8367327/log.txt)

**Comment by alextran1502** [comment]
Fixed in #83 

Please pull the repo and try again, thank you!

**Comment by Mattyfaz** [comment]
Confirmed working now! Thanks @alextran1502 :)
