### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by comfreak89** [alextran1502/immich#90]
.env file:

```
# STAGE
NODE_ENV=development

# Database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=/mnt/data/Immich

# JWT SECRET
JWT_SECRET=mNQXf1R6S1m7jwvwW82e

# MAPBOX
## ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=
```

UPLOAD_LOCATION exists:
```
root@docker:~/immich/immich-1.4.0-dev# ls -l /mnt/data/Immich/
total 0
```

```
root@docker:~/immich/immich-1.4.0-dev# docker-compose -f ./docker/docker-compose.yml up --build -V
WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
Building immich_microservices
ERROR: forbidden path outside the build context: ../microservices/Dockerfile ()
```

I dont know why the warnings appear, altough a .env file exists and the variables are filled:
```
root@docker:~/immich/immich-1.4.0-dev# ls -la docker/.env
-rw-rw-r-- 1 root root 327 Mar 29 23:44 docker/.env
```

**Comment by Klutronic** [comment]
Not seeing the warnings but I am getting the same error:

    Building immich_microservices
    ERROR: forbidden path outside the build context: ../microservices/Dockerfile ()

**Comment by jrasm91** [comment]
Probably need to run the `docker-compose` command up the top level directory, instead of inside the `docker/` folder.

**Comment by comfreak89** [comment]
I did as you can see in my commands. I am not in the docker folder when running the docker-compose command!

**Comment by jrasm91** [comment]
> I did as you can see in my commands. I am not in the docker folder when running the docker-compose command!

Ah, yes I see that now. My bad!

**Comment by alextran1502** [comment]
@comfreak89 I see that you downloaded the release, it was having a problem. I am about to push out another release to solve that problem. You can check out the main branch in the meantime to run. 

@Klutronic Did you also download and use the release version?

**Comment by Klutronic** [comment]
@alextran1502 I cloned the repo to run it

I am on Ubuntu 20.04.2: 

:~/docker/immich/immich$ docker-compose -v
docker-compose version 1.25.0, build unknown
:~/docker/immich/immich$ docker -v
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

**Comment by alextran1502** [comment]
Did you install docker with `snap`? Maybe related to #67

**Comment by comfreak89** [comment]
Hi,

I tried 1.4.0-7-dev and a direct clone of the repository now. Same issue.

Direct clone:
```
root@docker:~/immich/immich# docker-compose -f ./docker/docker-compose.yml up --build -V
WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
Building immich_microservices
ERROR: forbidden path outside the build context: ../microservices/Dockerfile ()
```

1.4.0-7-dev:
```
root@docker:~/immich/immich-1.4.0-7-dev# docker-compose -f ./docker/docker-compose.yml up --build -V
WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
Building immich_microservices
ERROR: forbidden path outside the build context: ../microservices/Dockerfile ()
```

I am still corious why it says, that the variables in the .env are not set, althout it is available:

Direct clone:
```
root@docker:~/immich/immich# ls -la docker/.env
-rw-r--r-- 1 root root 376 Mar 30 14:13 docker/.env
root@docker:~/immich/immich-1.4.0-7-dev# cat docker/.env
# STAGE
NODE_ENV=development

# Database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=/mnt/data/Immich

# JWT SECRET
JWT_SECRET=ganXupoCQdV9rcTiM0DSxDmwP5vCB4UIfeUjhogzr1EpDloucvq2UAQd1bfk

# MAPBOX
## ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=
```

1.4.0-7-dev:
```
root@docker:~/immich/immich-1.4.0-7-dev# ls -la docker/.env
-rw-r--r-- 1 root root 376 Mar 30 14:12 docker/.env
root@docker:~/immich/immich# cat docker/.env
# STAGE
NODE_ENV=development

# Database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=/mnt/data/Immich

# JWT SECRET
JWT_SECRET=ganXupoCQdV9rcTiM0DSxDmwP5vCB4UIfeUjhogzr1EpDloucvq2UAQd1bfk

# MAPBOX
## ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=
```

No, I installed docker via apt. Snap is not available.

```
root@docker:~/immich/immich/docker# apt list --installed | grep docker

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker-ce-cli/focal,now 5:20.10.12~3-0~ubuntu-focal amd64 [installed,upgradable to: 5:20.10.14~3-0~ubuntu-focal]
docker-ce-rootless-extras/focal,now 5:20.10.12~3-0~ubuntu-focal amd64 [installed,upgradable to: 5:20.10.14~3-0~ubuntu-focal]
docker-ce/focal,now 5:20.10.12~3-0~ubuntu-focal amd64 [installed,upgradable to: 5:20.10.14~3-0~ubuntu-focal]
docker-compose/focal,now 1.25.0-1 all [installed]
docker-scan-plugin/focal,now 0.12.0~ubuntu-focal amd64 [installed,upgradable to: 0.17.0~ubuntu-focal]
python3-docker/focal,now 4.1.0-1 all [installed,automatic]
python3-dockerpty/focal,now 0.4.1-2 all [installed,automatic]
root@docker:~/immich/immich/docker# snap list

Command 'snap' not found, but can be installed with:

apt install snapd
```

In my case, the host is a LXC Container on the newest Proxmox Version.

root@docker:~/immich/immich/docker# lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
root@docker:~/immich/immich/docker# uname -r
5.13.19-4-pve
root@docker:~/immich/immich-1.4.0-7-dev# docker-compose -v
docker-compose version 1.25.5, build 8a1c60f6
root@docker:~/immich/immich-1.4.0-7-dev# docker -v
Docker version 20.10.12, build e91ed57
```

**Comment by alextran1502** [comment]
@jrasm91 can you try to run this in a VM instead of LXC. I've had problems running Docker in LXC. 

Please take a look at the Known Issue with PromoxVM in the last section of Readme file

**Comment by Klutronic** [comment]
@alextran1502 I installed Docker with APT

**Comment by alextran1502** [comment]
@Klutronic Are you running this on a VM/LXC or your desktop environment?

**Comment by alextran1502** [comment]
@Klutronic Then there shouldn't be any problem. Hmm, this is strange. Can you try to reclone the repo and run it again? 

Can you also share your `docker-compose` and `.env` file?

**Comment by alextran1502** [comment]
@Klutronic Is there a reason you changed the version from 3.8 to 3.7?

Can you try commenting out the `immich_microservices` section to see if it makes any difference?

**Comment by comfreak89** [comment]
> @Klutronic Is there a reason you changed the version from 3.8 to 3.7?
> 
> Can you try commenting out the `immich_microservices` section to see if it makes any difference?

I also tried that. No difference despite that it tries to build the immich_server:

```
root@docker:~/immich/immich# docker-compose -f ./docker/docker-compose.yml up --build -V --force-recreate
WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
Creating network "docker_immich_network" with the default driver
Creating volume "docker_pgdata" with default driver
Building immich_server
ERROR: forbidden path outside the build context: ../server/Dockerfile ()
```

**Comment by alextran1502** [comment]
@comfreak89 Yeah, so it would probably be a problem with LXC then. Strange!

**Comment by Klutronic** [comment]
@alextran1502 Yes, I am not on a version of docker-compose that supports 3.8 so I went down to 3.7.

After commenting out the immich_microservices:

    sudo docker-compose -f ./docker/docker-compose.yml up --build -V
    WARNING: The UPLOAD_LOCATION variable is not set. Defaulting to a blank string.
    WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
    WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
    WARNING: The DB_DATABASE_NAME variable is not set. Defaulting to a blank string.
    Building immich_server
    ERROR: forbidden path outside the build context: ../server/Dockerfile ()

**Comment by alextran1502** [comment]
@comfreak89 Yes, I think your proposal is better. I will add them in future updates.

@Klutronic Can you try the solution proposed by @comfreak89 above?

**Comment by Klutronic** [comment]
@alextran1502 It seems to be up and running but I am getting the following error when I try to go to the site:

    {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}

**Comment by comfreak89** [comment]
Great!

The error is absolutely correct - there is no WebUI right now. You have to create a user with the curl command and from there on you can use the mobile app.

Change IP, email and password to your needs:
```
curl --location --request POST 'http://your-server-ip:2283/auth/signUp' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "testuser@email.com",
    "password": "password"
}'
```

**Comment by alextran1502** [comment]
@Klutronic You will need the mobile app (since this application is for mobile's media file backup), there is no web interface just yet

**Comment by Klutronic** [comment]
Ahhhhhh, OK!  I created the user already so I am good to go!  Thanks guys, I really appreciate the help!

**Comment by alextran1502** [comment]
Thanks, @comfreak89 and @Klutronic for improving the project :) cheers!

**Comment by amatorkoleksiyoner** [comment]
I had same error. My postgres password had . in it. I removed it in pgAdmin then errors gone.
