### ISSUE TITLE
Container docker_immich_microservice crush

### ISSUE THREAD

**Issue by HowWof** [alextran1502/immich#95]
Hello I have a problem in which this container crashes giving this information
Illegal instruction (core dumped)
> nest_microservices@0.0.1 prebuild
> rimraf dist
> nest_microservices@0.0.1 build
> nest build
> nest_microservices@0.0.1 start:prod
> node dist/main
Illegal instruction (core dumped)
The interesting thing is that besides the startup. Immich works without this container

**Comment by alextran1502** [comment]
Can you check this [Known Issue](https://github.com/alextran1502/immich#known-issue) in the readme and check if there is anything different?

**Comment by HowWof** [comment]
Cpu:AMD Ryzen 7 3800X
architecture x86

**Comment by alextran1502** [comment]
My suspect is that this is a 32-bit system so there might be a problem there. I haven't tested on a 32-bit system. Most of my tests run on a 64-bit system. Is this a permanent system or can you change to a different 64-bit vps?

**Comment by alextran1502** [comment]
I found this on Tensorflow website 
![image](https://user-images.githubusercontent.com/27055614/160887244-e7c235a3-d355-4342-98a4-81e98ef2896f.png)

**Comment by HowWof** [comment]
Can I just delete this container if it doesn't work anyway?
Do you plan to make versions without tensorflow?

**Comment by alextran1502** [comment]
Yes, you can delete that container since it deals with Machine learning features without affecting the core functionalities. However, without TensorFlow, it cannot really perform object detection and image classification and future facial recognition.

**Comment by HowWof** [comment]
Docker exit code 132
nest_microservices@0.0.1 prebuild
rimraf dist
nest_microservices@0.0.1 build
nest build
nest_microservices@0.0.1 start:prod
node dist/main
Illegal instruction (core dumped)

**Comment by alextran1502** [comment]
The crash issue is probably fixed in #97
